language: node_js
node_js:
    - "6.1"
before_install:
    - npm uninstall -g gitbook
    - npm install -g gitbook-cli
install:
    - npm install
script:
    - gitbook build
    - ./jenkins/sync-book-to-qiniu.sh
